# Generated by Django 6.0.5 on 2026-05-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiotAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puuid', models.CharField(max_length=128, unique=True)),
                ('game_name', models.CharField(max_length=100)),
                ('tag_line', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'riot_account',
                'indexes': [models.Index(fields=['puuid'], name='riot_account_puuid_idx'), models.Index(fields=['game_name', 'tag_line', 'region'], name='riot_account_riot_id_idx')],
                'constraints': [models.UniqueConstraint(fields=('game_name', 'tag_line', 'region'), name='unique_riot_id_per_region')],
            },
        ),
    ]
