# Generated by Django 6.0.5 on 2026-05-18 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMatchPhaseMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puuid', models.CharField(db_index=True, max_length=128)),
                ('champion_id', models.PositiveIntegerField()),
                ('position', models.CharField(blank=True, max_length=20)),
                ('lane_cs_diff_10', models.IntegerField(blank=True, null=True)),
                ('lane_gold_diff_10', models.IntegerField(blank=True, null=True)),
                ('lane_xp_diff_10', models.IntegerField(blank=True, null=True)),
                ('death_before_14', models.BooleanField(default=False)),
                ('objective_death_count', models.PositiveSmallIntegerField(default=0)),
                ('teamfight_participation', models.DecimalField(blank=True, decimal_places=2, help_text='Percent participation in identified teamfight events.', max_digits=5, null=True)),
                ('side_death_count', models.PositiveSmallIntegerField(default=0)),
                ('lane_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('objective_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('teamfight_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('side_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_metrics', to='matches.match')),
            ],
            options={
                'db_table': 'player_match_phase_metric',
                'indexes': [models.Index(fields=['puuid'], name='phase_metric_puuid_idx'), models.Index(fields=['champion_id', 'position'], name='phase_metric_champ_pos_idx'), models.Index(fields=['match', 'position'], name='phase_metric_match_pos_idx')],
                'constraints': [models.UniqueConstraint(fields=('match', 'puuid'), name='unique_phase_metric_per_match_player')],
            },
        ),
    ]
