# Generated by Django 6.0.5 on 2026-05-18 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=32, unique=True)),
                ('game_version', models.CharField(blank=True, max_length=40)),
                ('queue_id', models.PositiveIntegerField()),
                ('game_start_time', models.DateTimeField()),
                ('game_duration', models.PositiveIntegerField(help_text='Game duration in seconds.')),
                ('winning_team_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'match',
                'indexes': [models.Index(fields=['match_id'], name='match_match_id_idx'), models.Index(fields=['queue_id', 'game_start_time'], name='match_queue_start_idx'), models.Index(fields=['game_version'], name='match_game_version_idx')],
            },
        ),
        migrations.CreateModel(
            name='MatchParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puuid', models.CharField(db_index=True, max_length=128)),
                ('participant_id', models.PositiveSmallIntegerField()),
                ('team_id', models.PositiveSmallIntegerField()),
                ('champion_id', models.PositiveIntegerField()),
                ('champion_name', models.CharField(max_length=80)),
                ('individual_position', models.CharField(blank=True, max_length=20)),
                ('win', models.BooleanField()),
                ('kills', models.PositiveSmallIntegerField(default=0)),
                ('deaths', models.PositiveSmallIntegerField(default=0)),
                ('assists', models.PositiveSmallIntegerField(default=0)),
                ('total_damage_dealt_to_champions', models.PositiveIntegerField(default=0)),
                ('total_damage_taken', models.PositiveIntegerField(default=0)),
                ('gold_earned', models.PositiveIntegerField(default=0)),
                ('total_minions_killed', models.PositiveIntegerField(default=0)),
                ('neutral_minions_killed', models.PositiveIntegerField(default=0)),
                ('vision_score', models.PositiveIntegerField(default=0)),
                ('wards_placed', models.PositiveIntegerField(default=0)),
                ('wards_killed', models.PositiveIntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='matches.match')),
            ],
            options={
                'db_table': 'match_participant',
                'indexes': [models.Index(fields=['puuid'], name='participant_puuid_idx'), models.Index(fields=['champion_name', 'individual_position'], name='participant_champ_pos_idx'), models.Index(fields=['match', 'team_id'], name='participant_match_team_idx')],
                'constraints': [models.UniqueConstraint(fields=('match', 'participant_id'), name='unique_participant_per_match'), models.UniqueConstraint(fields=('match', 'puuid'), name='unique_puuid_per_match')],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.PositiveIntegerField(help_text='Event timestamp in milliseconds.')),
                ('minute', models.PositiveSmallIntegerField()),
                ('event_type', models.CharField(max_length=60)),
                ('participant_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('killer_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('victim_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('assisting_participant_ids', models.JSONField(blank=True, default=list)),
                ('monster_type', models.CharField(blank=True, max_length=40)),
                ('building_type', models.CharField(blank=True, max_length=40)),
                ('lane_type', models.CharField(blank=True, max_length=40)),
                ('item_id', models.PositiveIntegerField(blank=True, null=True)),
                ('position_x', models.IntegerField(blank=True, null=True)),
                ('position_y', models.IntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='matches.match')),
            ],
            options={
                'db_table': 'timeline_event',
                'indexes': [models.Index(fields=['match', 'minute'], name='event_match_minute_idx'), models.Index(fields=['event_type'], name='event_type_idx'), models.Index(fields=['monster_type'], name='event_monster_type_idx'), models.Index(fields=['victim_id', 'minute'], name='event_victim_minute_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimelineFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveSmallIntegerField()),
                ('participant_id', models.PositiveSmallIntegerField()),
                ('current_gold', models.PositiveIntegerField(default=0)),
                ('total_gold', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('minions_killed', models.PositiveIntegerField(default=0)),
                ('jungle_minions_killed', models.PositiveIntegerField(default=0)),
                ('position_x', models.IntegerField(blank=True, null=True)),
                ('position_y', models.IntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_frames', to='matches.match')),
            ],
            options={
                'db_table': 'timeline_frame',
                'indexes': [models.Index(fields=['match', 'minute'], name='frame_match_minute_idx'), models.Index(fields=['participant_id', 'minute'], name='frame_participant_minute_idx')],
                'constraints': [models.UniqueConstraint(fields=('match', 'minute', 'participant_id'), name='unique_frame_per_minute_participant')],
            },
        ),
    ]
